apiVersion: v1
data:
  acm-global-whats-changed.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 52,
      "iteration": 1681827493664,
      "links": [],
      "panels": [
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "fillOpacity": 70,
                "lineWidth": 0
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 10,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 50,
          "options": {
            "alignValue": "left",
            "legend": {
              "displayMode": "list",
              "placement": "bottom"
            },
            "mergeValues": true,
            "rowHeight": 0.9,
            "showValue": "auto",
            "tooltip": {
              "mode": "single"
            }
          },
          "title": "Panel Title",
          "type": "state-timeline"
        },
        {
          "collapsed": true,
          "datasource": null,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 10
          },
          "id": 46,
          "panels": [],
          "title": "Events",
          "type": "row"
        },
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "displayMode": "auto"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 11
          },
          "id": 48,
          "options": {
            "showHeader": true
          },
          "pluginVersion": "8.5.20",
          "title": "Panel Title",
          "type": "table"
        },
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "displayMode": "auto"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 11
          },
          "id": 49,
          "options": {
            "showHeader": true
          },
          "pluginVersion": "8.5.20",
          "title": "Panel Title",
          "type": "table"
        },
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "displayMode": "auto"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 11,
            "w": 24,
            "x": 0,
            "y": 19
          },
          "id": 47,
          "options": {
            "showHeader": true
          },
          "pluginVersion": "8.5.20",
          "title": "Panel Title",
          "type": "table"
        }
      ],
      "refresh": false,
      "schemaVersion": 30,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "PostgreSQL",
              "value": "PostgreSQL"
            },
            "description": null,
            "error": null,
            "hide": 2,
            "includeAll": false,
            "label": null,
            "multi": false,
            "name": "datasource",
            "options": [],
            "query": "postgres",
            "queryValue": "",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "type": "datasource"
          },
          {
            "allValue": null,
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": null,
            "definition": "SELECT\n  p.payload-> 'metadata' -> 'annotations' ->> 'policy.open-cluster-management.io/standards' AS \"policy_standard\"\nFROM\n  local_spec.policies p",
            "description": "Cluster policy standards",
            "error": {
              "config": {
                "data": {
                  "end": "1681827494",
                  "match[]": "SELECT\n  p.payload-> 'metadata' -> 'annotations' ->> 'policy.open-cluster-management.io/standards' AS \"policy_standard\"\nFROM\n  local_spec.policies p",
                  "start": "1681741094"
                },
                "headers": {
                  "Content-Type": "application/x-www-form-urlencoded",
                  "X-Grafana-Org-Id": 1
                },
                "hideFromInspector": true,
                "method": "POST",
                "retry": 0,
                "url": "api/datasources/proxy/1/api/v1/series"
              },
              "data": {
                "error": "Bad Request",
                "message": "cannot parse parameter match[]",
                "response": "cannot parse parameter match[]"
              },
              "message": "cannot parse parameter match[]",
              "status": 400,
              "statusText": "Bad Request"
            },
            "hide": 0,
            "includeAll": true,
            "label": "Standard",
            "multi": true,
            "name": "standard",
            "options": [],
            "query": {
              "query": "SELECT\n  p.payload-> 'metadata' -> 'annotations' ->> 'policy.open-cluster-management.io/standards' AS \"policy_standard\"\nFROM\n  local_spec.policies p",
              "refId": "Observatorium-standard-Variable-Query"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "allValue": null,
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": null,
            "definition": "SELECT\n  p.payload-> 'metadata' -> 'annotations' ->> 'policy.open-cluster-management.io/categories' AS \"policy_category\"\nFROM\n  local_spec.policies p\nWHERE\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/standards' IN ($standard)",
            "description": "Cluster policy categories",
            "error": {
              "config": {
                "data": {
                  "end": "1681827494",
                  "match[]": "SELECT\n  p.payload-> 'metadata' -> 'annotations' ->> 'policy.open-cluster-management.io/categories' AS \"policy_category\"\nFROM\n  local_spec.policies p\nWHERE\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/standards' IN (())",
                  "start": "1681741094"
                },
                "headers": {
                  "Content-Type": "application/x-www-form-urlencoded",
                  "X-Grafana-Org-Id": 1
                },
                "hideFromInspector": true,
                "method": "POST",
                "retry": 0,
                "url": "api/datasources/proxy/1/api/v1/series"
              },
              "data": {
                "error": "Bad Request",
                "message": "cannot parse parameter match[]",
                "response": "cannot parse parameter match[]"
              },
              "message": "cannot parse parameter match[]",
              "status": 400,
              "statusText": "Bad Request"
            },
            "hide": 0,
            "includeAll": true,
            "label": "Category",
            "multi": true,
            "name": "category",
            "options": [],
            "query": {
              "query": "SELECT\n  p.payload-> 'metadata' -> 'annotations' ->> 'policy.open-cluster-management.io/categories' AS \"policy_category\"\nFROM\n  local_spec.policies p\nWHERE\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/standards' IN ($standard)",
              "refId": "Observatorium-category-Variable-Query"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "allValue": null,
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": null,
            "definition": "SELECT\n  p.payload-> 'metadata' -> 'annotations' ->> 'policy.open-cluster-management.io/controls' AS \"policy_control\"\nFROM\n  local_spec.policies p\nWHERE\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/standards' IN ($standard)\nAND\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/categories' IN ($category)",
            "description": "Cluster policy controls",
            "error": {
              "config": {
                "data": {
                  "end": "1681827494",
                  "match[]": "SELECT\n  p.payload-> 'metadata' -> 'annotations' ->> 'policy.open-cluster-management.io/controls' AS \"policy_control\"\nFROM\n  local_spec.policies p\nWHERE\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/standards' IN (())\nAND\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/categories' IN (())",
                  "start": "1681741094"
                },
                "headers": {
                  "Content-Type": "application/x-www-form-urlencoded",
                  "X-Grafana-Org-Id": 1
                },
                "hideFromInspector": true,
                "method": "POST",
                "retry": 0,
                "url": "api/datasources/proxy/1/api/v1/series"
              },
              "data": {
                "error": "Bad Request",
                "message": "cannot parse parameter match[]",
                "response": "cannot parse parameter match[]"
              },
              "message": "cannot parse parameter match[]",
              "status": 400,
              "statusText": "Bad Request"
            },
            "hide": 0,
            "includeAll": true,
            "label": "Control",
            "multi": true,
            "name": "control",
            "options": [],
            "query": {
              "query": "SELECT\n  p.payload-> 'metadata' -> 'annotations' ->> 'policy.open-cluster-management.io/controls' AS \"policy_control\"\nFROM\n  local_spec.policies p\nWHERE\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/standards' IN ($standard)\nAND\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/categories' IN ($category)",
              "refId": "Observatorium-control-Variable-Query"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "allValue": null,
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": null,
            "definition": "SELECT\n  jsonb_array_elements(p.payload-> 'spec' -> 'policy-templates') -> 'objectDefinition' -> 'spec' ->> 'severity' as \"severity\"\nFROM local_spec.policies p\nWHERE\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/standards' IN ($standard)\nAND\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/categories' IN ($category)\nAND\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/controls' IN ($control)",
            "description": "Cluster policy severity",
            "error": {
              "config": {
                "data": {
                  "end": "1681827494",
                  "match[]": "SELECT\n  jsonb_array_elements(p.payload-> 'spec' -> 'policy-templates') -> 'objectDefinition' -> 'spec' ->> 'severity' as \"severity\"\nFROM local_spec.policies p\nWHERE\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/standards' IN (())\nAND\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/categories' IN (())\nAND\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/controls' IN (())",
                  "start": "1681741094"
                },
                "headers": {
                  "Content-Type": "application/x-www-form-urlencoded",
                  "X-Grafana-Org-Id": 1
                },
                "hideFromInspector": true,
                "method": "POST",
                "retry": 0,
                "url": "api/datasources/proxy/1/api/v1/series"
              },
              "data": {
                "error": "Bad Request",
                "message": "cannot parse parameter match[]",
                "response": "cannot parse parameter match[]"
              },
              "message": "cannot parse parameter match[]",
              "status": 400,
              "statusText": "Bad Request"
            },
            "hide": 0,
            "includeAll": true,
            "label": "Severity",
            "multi": true,
            "name": "severity",
            "options": [],
            "query": {
              "query": "SELECT\n  jsonb_array_elements(p.payload-> 'spec' -> 'policy-templates') -> 'objectDefinition' -> 'spec' ->> 'severity' as \"severity\"\nFROM local_spec.policies p\nWHERE\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/standards' IN ($standard)\nAND\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/categories' IN ($category)\nAND\n  p.payload->'metadata'-> 'annotations'->> 'policy.open-cluster-management.io/controls' IN ($control)",
              "refId": "Observatorium-severity-Variable-Query"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-24h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "utc",
      "title": "Global Hub - What's Changed",
      "uid": "fad31bbc6806481ea0434b509eb53fbc",
      "version": 1
    }
kind: ConfigMap
metadata:
  name: grafana-dashboard-acm-global-whats-changed
  namespace: {{.Namespace}}